### ISSUE TITLE
Support local service discovery BEP 14

### ISSUE THREAD

**Issue by RangerMauve** [webtorrent/torrent-discovery#44]
I've been having trouble getting clients to seed to each other either on the same machine or on the same network (on a home network).

Another concern is that the reliance on the DHT / Trackers means that you can't discover peers if you're not connected to the internet at large.

Would a PR that adds support for [BEP 14](http://www.bittorrent.org/beps/bep_0014.html) be welcome?

**Comment by epvbergen** [comment]
I'm also very interested in that functionality. However can it work? If webtorrent runs on top of webrtc, local discovery using multicast requires that the browser-based webrtc can join multicast addresses using SDP. Or something in that vein. I've looked at the specs but there's no indication that that is even a thing... I so dearly hope I'm missing something and don't need to bundle some kind of service that would need to be installed.

**Comment by RangerMauve** [comment]
Yeah, I think the local discovery would only work in node.js. :(

**Comment by pataquets** [comment]
I would love to see this implemented, too.
Even when not working under WebRTC, lots of NodeJS projects use this lib.
This one could benefit, for instance:  mafintosh/torrent-stream#204
Big +1 here.

**Comment by pataquets** [comment]
@feross Any feedback about @RangerMauve offer? (Or somebody else)

**Comment by feross** [comment]
Really nice PR to solve this issue here: https://github.com/webtorrent/torrent-discovery/pull/48
